In [100]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [101]:
data = pd.read_csv('jj.csv')

In [102]:
print(data)

   sr no  training_set(0) / test_set(1)                     image
0      1                              1        image set/1/11.jpg
1      2                              0       image set/1/112.jpg
2      3                              0      image set/1/1112.jpg
3      4                              0      image set/2/7676.jpg
4      5                              1      image set/2/8787.jpg
5      6                              1     image set/3/23243.jpg
6      7                              1  image set/3/Untitled.jpg


In [103]:
x = data.iloc[:, 1].values
y = data.iloc[:, -1].values

In [104]:
print(x)
print(y)

[1 0 0 0 1 1 1]
['image set/1/11.jpg' 'image set/1/112.jpg' 'image set/1/1112.jpg'
 'image set/2/7676.jpg' 'image set/2/8787.jpg' 'image set/3/23243.jpg'
 'image set/3/Untitled.jpg']


In [105]:
c = 0
for n in x:
    if n==0:
        c+=1
print(c)    

3


In [106]:
c = [n for n in x if n==0]

In [107]:
print(c)

[0, 0, 0]


In [108]:
rf = data.iloc[:,[1,2]].values

In [109]:
print(rf)

[[1 'image set/1/11.jpg']
 [0 'image set/1/112.jpg']
 [0 'image set/1/1112.jpg']
 [0 'image set/2/7676.jpg']
 [1 'image set/2/8787.jpg']
 [1 'image set/3/23243.jpg']
 [1 'image set/3/Untitled.jpg']]


In [110]:
hh = rf[:,1]

In [111]:
print(hh)

['image set/1/11.jpg' 'image set/1/112.jpg' 'image set/1/1112.jpg'
 'image set/2/7676.jpg' 'image set/2/8787.jpg' 'image set/3/23243.jpg'
 'image set/3/Untitled.jpg']


In [112]:
g = np.array(['E:/j/' + j for j in rf[:,1]])

In [113]:
print(g)

['E:/j/image set/1/11.jpg' 'E:/j/image set/1/112.jpg'
 'E:/j/image set/1/1112.jpg' 'E:/j/image set/2/7676.jpg'
 'E:/j/image set/2/8787.jpg' 'E:/j/image set/3/23243.jpg'
 'E:/j/image set/3/Untitled.jpg']


In [114]:
print(rf)

[[1 'image set/1/11.jpg']
 [0 'image set/1/112.jpg']
 [0 'image set/1/1112.jpg']
 [0 'image set/2/7676.jpg']
 [1 'image set/2/8787.jpg']
 [1 'image set/3/23243.jpg']
 [1 'image set/3/Untitled.jpg']]


In [115]:
rf[:,1] = g[:]

In [116]:
print(rf)

[[1 'E:/j/image set/1/11.jpg']
 [0 'E:/j/image set/1/112.jpg']
 [0 'E:/j/image set/1/1112.jpg']
 [0 'E:/j/image set/2/7676.jpg']
 [1 'E:/j/image set/2/8787.jpg']
 [1 'E:/j/image set/3/23243.jpg']
 [1 'E:/j/image set/3/Untitled.jpg']]


In [117]:
e1 = np.array([g for g in rf if np.all(g)])

In [118]:
print(e1,'\n\n',e1[:,1])

[[1 'E:/j/image set/1/11.jpg']
 [1 'E:/j/image set/2/8787.jpg']
 [1 'E:/j/image set/3/23243.jpg']
 [1 'E:/j/image set/3/Untitled.jpg']] 

 ['E:/j/image set/1/11.jpg' 'E:/j/image set/2/8787.jpg'
 'E:/j/image set/3/23243.jpg' 'E:/j/image set/3/Untitled.jpg']


In [119]:
e2 = np.array([g for g in rf if not np.all(g)])

In [120]:
print(e2)

[[0 'E:/j/image set/1/112.jpg']
 [0 'E:/j/image set/1/1112.jpg']
 [0 'E:/j/image set/2/7676.jpg']]


In [127]:
from shutil import copy2
import os, sys

In [132]:
for i in e1[:,1]:
    if 'image set/1' in i:
        #os.mkdir('E:/j/train/1')
        copy2(i, 'E:/j/train/1')
    if 'image set/2' in i:
        #os.mkdir('E:/j/train/2')
        copy2(i, 'E:/j/train/2')   
    if 'image set/3' in i:
        #os.mkdir('E:/j/train/3')
        copy2(i, 'E:/j/train/3')        

In [133]:
for i in e2[:,1]:
    if 'image set/1' in i:
        #os.mkdir('E:/j/train/1')
        copy2(i, 'E:/j/test/1')
    if 'image set/2' in i:
        #os.mkdir('E:/j/train/2')
        copy2(i, 'E:/j/test/2')   
    if 'image set/3' in i:
        #os.mkdir('E:/j/train/3')
        copy2(i, 'E:/j/test/3')  

In [134]:
import glob

In [157]:
h = np.array(glob.glob("E:\CUB_200_2011\images\*"))

In [165]:
print(h[1])

E:\CUB_200_2011\images\002.Laysan_Albatross


In [166]:
l = h[1]   

In [178]:
print(l)

E:\CUB_200_2011\images\002.Laysan_Albatross


In [191]:
l[23:]

'002.Laysan_Albatross'

In [192]:
mm = [u[23:] for u in h]

In [193]:
print(mm)

['001.Black_footed_Albatross', '002.Laysan_Albatross', '003.Sooty_Albatross', '004.Groove_billed_Ani', '005.Crested_Auklet', '006.Least_Auklet', '007.Parakeet_Auklet', '008.Rhinoceros_Auklet', '009.Brewer_Blackbird', '010.Red_winged_Blackbird', '011.Rusty_Blackbird', '012.Yellow_headed_Blackbird', '013.Bobolink', '014.Indigo_Bunting', '015.Lazuli_Bunting', '016.Painted_Bunting', '017.Cardinal', '018.Spotted_Catbird', '019.Gray_Catbird', '020.Yellow_breasted_Chat', '021.Eastern_Towhee', '022.Chuck_will_Widow', '023.Brandt_Cormorant', '024.Red_faced_Cormorant', '025.Pelagic_Cormorant', '026.Bronzed_Cowbird', '027.Shiny_Cowbird', '028.Brown_Creeper', '029.American_Crow', '030.Fish_Crow', '031.Black_billed_Cuckoo', '032.Mangrove_Cuckoo', '033.Yellow_billed_Cuckoo', '034.Gray_crowned_Rosy_Finch', '035.Purple_Finch', '036.Northern_Flicker', '037.Acadian_Flycatcher', '038.Great_Crested_Flycatcher', '039.Least_Flycatcher', '040.Olive_sided_Flycatcher', '041.Scissor_tailed_Flycatcher', '042.Ver

In [194]:
print(len(mm))

200


In [195]:
vgg_dir = 'E:\\CUB_200_2011\\train\\'
for i in mm:
    os.mkdir(vgg_dir + i)

In [196]:
vgg_dir = 'E:\\CUB_200_2011\\test\\'
for i in mm:
    os.mkdir(vgg_dir + i)

In [198]:
d = pd.read_csv('E:\CUB_200_2011\image123.csv')

In [199]:
print(d)

       sr no  test-set(0)/ training-set(1)  \
0          1                             0   
1          2                             1   
2          3                             0   
3          4                             1   
4          5                             1   
5          6                             0   
6          7                             1   
7          8                             1   
8          9                             1   
9         10                             0   
10        11                             1   
11        12                             0   
12        13                             0   
13        14                             0   
14        15                             1   
15        16                             0   
16        17                             0   
17        18                             1   
18        19                             0   
19        20                             1   
20        21                      

In [202]:
rf = d.iloc[:,[1,2]].values

In [203]:
print(rf)

[[0 '001.Black_footed_Albatross/Black_Footed_Albatross_0046_18.jpg']
 [1 '001.Black_footed_Albatross/Black_Footed_Albatross_0009_34.jpg']
 [0 '001.Black_footed_Albatross/Black_Footed_Albatross_0002_55.jpg']
 ..., 
 [0 '200.Common_Yellowthroat/Common_Yellowthroat_0008_190703.jpg']
 [1 '200.Common_Yellowthroat/Common_Yellowthroat_0049_190708.jpg']
 [0 '200.Common_Yellowthroat/Common_Yellowthroat_0055_190967.jpg']]


In [204]:
hh = rf[:,1]

In [205]:
hh

array(['001.Black_footed_Albatross/Black_Footed_Albatross_0046_18.jpg',
       '001.Black_footed_Albatross/Black_Footed_Albatross_0009_34.jpg',
       '001.Black_footed_Albatross/Black_Footed_Albatross_0002_55.jpg',
       ..., '200.Common_Yellowthroat/Common_Yellowthroat_0008_190703.jpg',
       '200.Common_Yellowthroat/Common_Yellowthroat_0049_190708.jpg',
       '200.Common_Yellowthroat/Common_Yellowthroat_0055_190967.jpg'], dtype=object)

In [206]:
g = np.array(['E:/CUB_200_2011/images/' + j for j in rf[:,1]])

In [207]:
print(g)

[ 'E:/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0046_18.jpg'
 'E:/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0009_34.jpg'
 'E:/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0002_55.jpg'
 ...,
 'E:/CUB_200_2011/images/200.Common_Yellowthroat/Common_Yellowthroat_0008_190703.jpg'
 'E:/CUB_200_2011/images/200.Common_Yellowthroat/Common_Yellowthroat_0049_190708.jpg'
 'E:/CUB_200_2011/images/200.Common_Yellowthroat/Common_Yellowthroat_0055_190967.jpg']


In [208]:
rf[:,1] = g[:]

In [209]:
print(rf)

[[0
  'E:/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0046_18.jpg']
 [1
  'E:/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0009_34.jpg']
 [0
  'E:/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0002_55.jpg']
 ..., 
 [0
  'E:/CUB_200_2011/images/200.Common_Yellowthroat/Common_Yellowthroat_0008_190703.jpg']
 [1
  'E:/CUB_200_2011/images/200.Common_Yellowthroat/Common_Yellowthroat_0049_190708.jpg']
 [0
  'E:/CUB_200_2011/images/200.Common_Yellowthroat/Common_Yellowthroat_0055_190967.jpg']]


In [210]:
e1 = np.array([g for g in rf if np.all(g)])

In [211]:
e2 = np.array([g for g in rf if not np.all(g)])

In [212]:
e1

array([[1,
        'E:/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0009_34.jpg'],
       [1,
        'E:/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0074_59.jpg'],
       [1,
        'E:/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0014_89.jpg'],
       ..., 
       [1,
        'E:/CUB_200_2011/images/200.Common_Yellowthroat/Common_Yellowthroat_0094_190690.jpg'],
       [1,
        'E:/CUB_200_2011/images/200.Common_Yellowthroat/Common_Yellowthroat_0037_190698.jpg'],
       [1,
        'E:/CUB_200_2011/images/200.Common_Yellowthroat/Common_Yellowthroat_0049_190708.jpg']], dtype=object)

In [213]:
e2

array([[0,
        'E:/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0046_18.jpg'],
       [0,
        'E:/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0002_55.jpg'],
       [0,
        'E:/CUB_200_2011/images/001.Black_footed_Albatross/Black_Footed_Albatross_0085_92.jpg'],
       ..., 
       [0,
        'E:/CUB_200_2011/images/200.Common_Yellowthroat/Common_Yellowthroat_0058_190958.jpg'],
       [0,
        'E:/CUB_200_2011/images/200.Common_Yellowthroat/Common_Yellowthroat_0008_190703.jpg'],
       [0,
        'E:/CUB_200_2011/images/200.Common_Yellowthroat/Common_Yellowthroat_0055_190967.jpg']], dtype=object)

In [216]:
for p in range(200):
    k = mm[p]
    for i in e1[:,1]:
        if 'images/' + k in i:
            copy2(i, 'E:/CUB_200_2011/train/'+k)    

In [217]:
for p in range(200):
    k = mm[p]
    for i in e2[:,1]:
        if 'images/' + k in i:
            copy2(i, 'E:/CUB_200_2011/test/'+k)    